# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Australia/Sydney"
    open-pull-requests-limit: 10
    reviewers:
      - "Theprofitplatform"
    assignees:
      - "Theprofitplatform"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "npm"
      prefix-development: "npm(dev)"
      include: "scope"
    # Group updates for better PR management
    groups:
      astro:
        patterns:
          - "@astrojs/*"
          - "astro"
      testing:
        patterns:
          - "vitest*"
          - "@vitest/*"
          - "playwright"
          - "@playwright/*"
      linting:
        patterns:
          - "eslint*"
          - "prettier"
      development:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    # Security updates always allowed
    allow:
      - dependency-type: "all"
    # Ignore major updates for stable dependencies (review manually)
    ignore:
      - dependency-name: "astro"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@astrojs/*"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Australia/Sydney"
    open-pull-requests-limit: 5
    reviewers:
      - "Theprofitplatform"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
