name = "tpp"
compatibility_date = "2024-09-28"
pages_build_output_dir = "dist"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "tpp-production"
compatibility_flags = ["nodejs_compat"]