services:
  - type: web
    name: tpp-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: SERPAPI_KEY
        sync: false
