#!/bin/bash

# Quickest setup - just open n8n and import!

N8N_URL="https://n8n.theprofitplatform.com.au"
WORKFLOW_FILE="/home/avi/projects/astro-site/n8n-workflows/tool-improvement-agent-workflow.json"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⚡ FASTEST Setup (3 clicks)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  Open n8n:"
echo "   $N8N_URL"
echo ""
echo "2️⃣  Import workflow:"
echo "   • Click 'Workflows' → '+ Add Workflow'"
echo "   • Menu (⋮) → 'Import from File'"
echo "   • Select: $WORKFLOW_FILE"
echo ""
echo "3️⃣  Configure Gmail (one-time):"
echo "   • Click 'Send Gmail' node"
echo "   • Set up OAuth2 credential"
echo "   • Instructions: $N8N_URL/workflows"
echo ""
echo "4️⃣  Activate:"
echo "   • Toggle 'Active' switch"
echo "   • Done! ✅"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📧 You'll receive improvement reports every 30 minutes!"
echo ""
echo "For detailed Gmail OAuth setup, see:"
echo "  cat $SCRIPT_DIR/QUICK-START.md"
echo ""
