import { readFile } from 'fs/promises';
import nodemailer from 'nodemailer';
import dotenv from 'dotenv';

dotenv.config({ path: '/home/avi/projects/astro-site/.env.tool-agent' });

const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST,
  port: parseInt(process.env.SMTP_PORT),
  secure: false,
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS
  }
});

console.log('Testing email...');

const mailOptions = {
  from: process.env.EMAIL_FROM,
  to: process.env.EMAIL_TO,
  subject: '[Tool Agent Test] Rank Tracker - 4 Improvements Found',
  text: `🤖 Tool Improvement Agent - Test Email

Tool Analyzed: Rank Tracker
Type: seo
Status: active
Priority: high
Completeness: 60%
User Value: 70/100

4 Improvements Suggested:

1. Replace Mock Data with Real API - CRITICAL
Replace mock data with SerpAPI or DataForSEO API for real-time SERP data.

2. Add Historical tracking/charts - HIGH
Track ranking changes over time with visual charts.

3. Add Export functionality - MEDIUM
Allow users to download results as PDF or CSV.

4. Add Batch keyword tracking - MEDIUM
Enable tracking multiple keywords simultaneously.

This email was automatically generated by the Tool Improvement Agent.
Total cycles completed: 1`
};

await transporter.sendMail(mailOptions);
console.log('✅ Test email sent! Check your inbox at', process.env.EMAIL_TO);
