name: Parity Guardrail

on:
  push:
    branches: [ "main" ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: node scripts/verify.mjs cloudflare
        env:
          PROD_URL: https://theprofitplatform.com.au/
          PREVIEW_URL: https://tpp.pages.dev/